exposicio:
    pattern:  /exposicio
    defaults: { _controller: BellesCosesFalsesMainBundle:Exposicio:index }

artistes:
    pattern:  /artistes
    defaults: { _controller: BellesCosesFalsesMainBundle:Artistes:index }

activitats:
    pattern:  /activitats
    defaults: { _controller: BellesCosesFalsesMainBundle:Activitats:index }

agraiments:
    pattern:  /agraiments
    defaults: { _controller: BellesCosesFalsesMainBundle:Agraiments:index }

blog:
    pattern:  /blog
    defaults: { _controller: BellesCosesFalsesMainBundle:Blog:index }

credits:
    pattern:  /credits
    defaults: { _controller: BellesCosesFalsesMainBundle:Credits:index }

############################ GLOBALS
sitemap:
    pattern:        /sitemap/
    defaults:       { _controller: BellesCosesFalsesMainBundle:Default:sitemap, _format: xml }

home:
    pattern:        /
    defaults:       { _controller: BellesCosesFalsesMainBundle:Default:index }