imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @OhInstagramBundle/Resources/config/services.yml }
    #- { resource: services.xml }

framework:
    #esi:             ~
    translator:      ~  # original config before SonataAdmin { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  ca
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'FluxPageBundle:Admin:form.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
            ApplicationSonataUserBundle: ~
            SonataUserBundle: ~
            FOSUserBundle: ~

# Stof Doctrine Extensions (Translatable)
stof_doctrine_extensions:
    default_locale: ca
    translation_fallback: true
    orm:
        default:
            translatable: true
            sluggable: true

# a2Lix Sonata Translations
a2lix_translation_form:
    locales: [ es, en ]

# Swiftmailer Configuration
swiftmailer:
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       %mail_host%
    username:   %mail_username%
    password:   %mail_password%
    spool:      { type: memory }

# Genemu Form Select 2 Bundle
genemu_form:
    date: ~

# TinyMCE
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    language: %locale%
    theme:
        # simple: ~
        simple:   # original theme "advanced"
            plugins:
                - "advlist autolink lists link charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime nonbreaking save contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "undo redo | styleselect | bold italic underline | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link | print preview"
            image_advtab: true
            templates:
                - {title: 'Test template 1', content: 'Test 1'}
                - {title: 'Test template 2', content: 'Test 2'}
        # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
        bbcode:
            plugins: ["bbcode, code, link, preview"]
            menubar: false
            toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"

# Vich Uploader Bundle
vich_uploader:
    db_driver: orm
    mappings:
        imatge:
            uri_prefix: /uploads/images
            upload_destination: %kernel.root_dir%/../web/uploads/images
            inject_on_load: false
            delete_on_remove: true
        article:
            uri_prefix: /uploads/posts
            upload_destination: %kernel.root_dir%/../web/uploads/posts
            inject_on_load: false
            delete_on_remove: true
        pdf:
            uri_prefix: /uploads/documents
            upload_destination: %kernel.root_dir%/../web/uploads/documents
            inject_on_load: false
            delete_on_remove: true

# Liip Imagine Bundle
liip_imagine:
    cache_prefix: /uploads/cache
    filter_sets:
        imatge380x380:
            quality: 90
            filters:
                thumbnail: { size: [380, 380], mode: outbound }
        imatge60x60:
            quality: 90
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
        imatge100x220:
            quality: 90
            filters:
                thumbnail: { size: [100, 220], mode: outbound }
        imatge140x307:
            quality: 90
            filters:
                thumbnail: { size: [140, 307], mode: outbound }
        imatge140x420:
            quality: 90
            filters:
                thumbnail: { size: [140, 420], mode: outbound }
        imatge167x500:
            quality: 90
            filters:
                thumbnail: { size: [167, 500], mode: outbound }
        imatge500x220:
            quality: 90
            filters:
                thumbnail: { size: [500, 220], mode: outbound }
        imatge620x220:
            quality: 90
            filters:
                thumbnail: { size: [620, 220], mode: outbound }
        imatge630xY:
            quality: 90
            filters:
                thumbnail: { size: [630, null], mode: outbound }
        imatge280xY:
            quality: 90
            filters:
                thumbnail: { size: [280, null], mode: outbound }

# KNP Paginator Bundle
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

# Sonata FOS User
sonata_user:
    security_acl: true
    class:                  # Entity Classes
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group
    admin:                  # Admin Classes
        user:
            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

# Friends Of Symfony (FOS)
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group

# Sonata Admin
sonata_admin:
    title:  'Belles Coses Falses · Administrador continguts'
    title_logo: '/favicon.png'
    templates:
        layout: BellesCosesFalsesMainBundle:Admin:standard_layout_tinymce.html.twig
        dashboard: BellesCosesFalsesMainBundle:Admin:my_dashboard.html.twig
        ajax: SonataAdminBundle::ajax_layout.html.twig
        list: SonataAdminBundle:CRUD:list.html.twig
        show: SonataAdminBundle:CRUD:show.html.twig
        edit: FluxPageBundle:Admin:edit.html.twig # antes SonataAdminBundle:CRUD:edit.html.twig en un update de Sonata salta un error en este recurso (linea 35)
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
        groups:
            Pàgines:
            Blog:

# Sonata Block
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:   ~
        sonata.block.service.action: ~
        sonata.block.service.rss:    ~

# DIC config
services:
    flux.admin.page:
        class: Flux\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pàgines, label: Pàgina }
        arguments: [null, Flux\PageBundle\Entity\Page, FluxPageBundle:PageAdmin]
    flux.admin.blog:
        class: Flux\BlogBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Blog, label: Article }
        arguments: [null, Flux\BlogBundle\Entity\Post, FluxBlogBundle:PostAdmin]