belles_coses_falses_main:
    resource: "@BellesCosesFalsesMainBundle/Resources/config/routing.yml"
    prefix:   /

maincontroller:
    resource: "@BellesCosesFalsesMainBundle/Controller/"
    type:     annotation
    prefix:   /

OhInstagramBundle:
    resource: "@OhInstagramBundle/Resources/config/routing.yml"
    prefix:   /

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

_imagine:
    resource:   .
    type:       imagine